# Create a program that will play the “cows and bulls” game with the user. The game works like this:
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number(Digits should not be repeated). For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” 
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.
# Say the number generated by the computer is 1038. An example interaction could look like this:
#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1250
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.

import random

def generate_number():
    """Generate a random 4-digit number with unique digits."""
    digits = random.sample(range(10), 4)  # Get 4 unique digits
    return ''.join(map(str, digits))

def get_cows_and_bulls(secret, guess):
    """Compare guess with secret number and count cows and bulls."""
    cows = sum(1 for i in range(4) if guess[i] == secret[i])
    bulls = sum(1 for i in range(4) if guess[i] in secret and guess[i] != secret[i])
    return cows, bulls

def is_valid_guess(guess):
    """Check if the guess is a 4-digit number with unique digits."""
    return len(guess) == 4 and guess.isdigit() and len(set(guess)) == 4

def play_game():
    """Main function to play the game."""
    secret_number = generate_number()
    attempts = 0

    print("Welcome to the Cows and Bulls Game!")
    
    while True:
        guess = input("Enter a 4-digit number (digits should not repeat): ")

        if not is_valid_guess(guess):
            print("Invalid input! Make sure you enter 4 unique digits.")
            continue
        
        attempts += 1
        cows, bulls = get_cows_and_bulls(secret_number, guess)
        
        print(f"{cows} cow(s), {bulls} bull(s)")

        if cows == 4:
            print(f"Congratulations! You guessed the number {secret_number} in {attempts} attempts.")
            break

play_game()
